// Implements Authorization API that simplifies usage of authorization scripts generated by Cartesian.
var cartesian = cartesian || {};
(function () {
  cartesian.auth = cartesian.auth || {};

  cartesian.auth.allPermissions = cartesian.auth.allPermissions || {};

  cartesian.auth.grantedPermissions = cartesian.auth.grantedPermissions || {};

  //Deprecated. Use cartesian.auth.isGranted instead.
  cartesian.auth.hasPermission = function (permissionName) {
    return cartesian.auth.isGranted.apply(this, arguments);
  };

  //Deprecated. Use cartesian.auth.isAnyGranted instead.
  cartesian.auth.hasAnyOfPermissions = function () {
    return cartesian.auth.isAnyGranted.apply(this, arguments);
  };

  //Deprecated. Use cartesian.auth.areAllGranted instead.
  cartesian.auth.hasAllOfPermissions = function () {
    return cartesian.auth.areAllGranted.apply(this, arguments);
  };

  cartesian.auth.isGranted = function (permissionName) {
    return (
        (cartesian.auth.allPermissions[permissionName] !== undefined && cartesian.auth.grantedPermissions[permissionName] !== undefined ) ||
        (cartesian.auth.allPermissions.indexOf(permissionName) !== -1 && cartesian.auth.grantedPermissions.indexOf(permissionName) !== -1)
    );
  };

  cartesian.auth.isAnyGranted = function () {
    if (!arguments || arguments.length <= 0) {
      return true;
    }

    for (var i = 0; i < arguments.length; i++) {
      if (cartesian.auth.isGranted(arguments[i])) {
        return true;
      }
    }

    return false;
  };

  cartesian.auth.areAllGranted = function () {
    if (!arguments || arguments.length <= 0) {
      return true;
    }

    for (var i = 0; i < arguments.length; i++) {
      if (!cartesian.auth.isGranted(arguments[i])) {
        return false;
      }
    }

    return true;
  };

  cartesian.auth.tokenCookieName = "Cartesian.AuthToken";

  cartesian.auth.setToken = function (authToken, expireDate) {
    cartesian.utils.setCookieValue(
      cartesian.auth.tokenCookieName,
      authToken,
      expireDate,
      cartesian.appPath,
      cartesian.domain
    );
  };

  cartesian.auth.getToken = function () {
    return cartesian.utils.getCookieValue(cartesian.auth.tokenCookieName);
  };

  cartesian.auth.clearToken = function () {
    cartesian.auth.setToken();
  };

  cartesian.auth.refreshTokenCookieName = "Cartesian.AuthRefreshToken";

  cartesian.auth.setRefreshToken = function (refreshToken, expireDate) {
    cartesian.utils.setCookieValue(
      cartesian.auth.refreshTokenCookieName,
      refreshToken,
      expireDate,
      cartesian.appPath,
      cartesian.domain
    );
  };

  cartesian.auth.getRefreshToken = function () {
    return cartesian.utils.getCookieValue(cartesian.auth.refreshTokenCookieName);
  };

  cartesian.auth.clearRefreshToken = function () {
    cartesian.auth.setRefreshToken();
  };
})();
