var cartesian = cartesian || {};
(function () {
  // Implements Settings API that simplifies usage of setting scripts generated by Cartesian.
  cartesian.setting = cartesian.setting || {};

  cartesian.setting.values = cartesian.setting.values || {};

  cartesian.setting.get = function (name) {
    return cartesian.setting.values[name];
  };

  cartesian.setting.getBoolean = function (name) {
    var value = cartesian.setting.get(name);
    return value == "true" || value == "True";
  };

  cartesian.setting.getInt = function (name) {
    return parseInt(cartesian.setting.values[name]);
  };
})();
