name: Bump version

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Semver type of new version (major / minor / patch)'
        options:
          - major
          - minor
          - patch
        required: true

jobs:
  bump-version:
    name: Bump version
    runs-on: ubuntu-latest
    steps:
      - name: Check out source
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.AUTOMATION_ACCESS_TOKEN }}
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Setup Git
        run: |
          git config user.name 'Cartesian Bot'
          git config user.email 'bot@cartesianui.com'
      - name: Bump version & tag commit
        run: npm version ${{ github.event.inputs.version }}

      - name: Push latest version
        run: git push origin main --follow-tags
